"""update food fields

Revision ID: fcd6cd3d9a28
Revises: bc128cb429d8
Create Date: 2026-08-23 00:44:59.114991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd6cd3d9a28'
down_revision = 'bc128cb429d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('english_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('thai_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('serving_size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_fats', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('saturated_fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_carbohydrates', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dietary_fibre', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sugars', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('carbohydrates')
        batch_op.drop_column('fat')
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('carbohydrates', sa.FLOAT(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('sodium')
        batch_op.drop_column('total_sugars')
        batch_op.drop_column('dietary_fibre')
        batch_op.drop_column('total_carbohydrates')
        batch_op.drop_column('cholesterol')
        batch_op.drop_column('saturated_fat')
        batch_op.drop_column('total_fats')
        batch_op.drop_column('serving_size')
        batch_op.drop_column('brand')
        batch_op.drop_column('thai_name')
        batch_op.drop_column('english_name')

    # ### end Alembic commands ###
